<!-- BEGIN (write your solution here) -->
<table>
    <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <?= htmlspecialchars($user['id']) ?>
            </td>
            <td>
                <a href="/users/<?= htmlspecialchars($user['id']) ?>"><?= htmlspecialchars($user['firstName']) ?></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<!-- END -->
