<a href="/users">Все Пользователи</a>

<!-- BEGIN (write your solution here) -->
<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" required />
    <input type="submit" value="Search" />
</form>

<?php foreach ($searchAnswer as $user): ?>
    <div>
        <?= htmlspecialchars($user['id']) ?> :
        <?= htmlspecialchars($user['nickname']) ?> :
        <?= htmlspecialchars($user['email']) ?>
    </div>
<?php endforeach ?>
<!-- END -->
