<a href="/my-users">Все Пользователи</a>

<form action="/my-users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" required />
    <input type="submit" value="Search" />
</form>

<table>
    <?php foreach ($searchAnswer as $user): ?>
        <tr>
            <td>
                <?= htmlspecialchars($user) ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>
